

paths:
  data_folder: data/

  geojson_raw: data/data_analysis_results/Geojson_pipelines/graphed_pipeline_network_threshold_20.geojson
  node_info: data/data_sources/node_info.xlsx
  generation_nodes: data/data_sources/generation_fields.xlsx

  geojson_output: data/data_analysis_results/Geojson_pipelines/study_case_network.geojson

  figures: study_case_model/figures/main_run/
  pickle_file: study_case_model/scenario_variables/main_model.pkl