

paths:

  ### Data files
  data_folder: data/

  geojson_raw: data/data_analysis_results/Geojson_pipelines/graphed_pipeline_network_threshold_20.geojson
  node_info: data/data_sources/node_info.xlsx
  generation_nodes: data/data_sources/generation_fields.xlsx

  geojson_output: data/data_analysis_results/Geojson_pipelines/study_case_network.geojson

  # Specific files
  bigger_network_geojson: data/data_analysis_results/Geojson_pipelines/bigger_network.geojson
  smaller_network_geojson: data/data_analysis_results/Geojson_pipelines/smaller_network.geojson
  graphed_pipeline_with_features: data/data_analysis_results/Geojson_pipelines/graphed_pipeline_network_with_features.geojson
  geojson_pipelines_folder: data/data_analysis_results/Geojson_pipelines/
  data_analysis_results: data/data_analysis_results/
  data_sources: data/data_sources/

  # HTML files
  graphed_pipeline_network: data/data_analysis_results/graphed_pipeline_network.html
  graphed_smaller_network: data/data_analysis_results/graphed_smaller_network.html
  graphed_bigger_network: data/data_analysis_results/graphed_bigger_network.html
  h2_norway_overlay_map: data/data_analysis_results/h2_norway_overlay_map.html


  ### Main run
  figures: study_case_model/figures/main_run/
  pickle_file: study_case_model/scenario_variables/main_model.pkl

  # Additional paths from Python files
  scenario_variables: study_case_model/scenario_variables/
  scenario_variables_other: study_case_model/scenario_variables/other_experiment_data/
  figures_cutting_plane: study_case_model/figures/cutting_plane_grid/
  bigger_network_scenario: study_case_model/bigger_network/scenario_variables/
  bigger_network_figures: study_case_model/bigger_network/figures/
  smaller_network_scenario: study_case_model/smaller_network/scenario_variables/
  smaller_network_figures: study_case_model/smaller_network/figures/
  unit_networks_solves_figures: study_case_model/unit_networks_solves/figures/
  unit_networks_solves_snapshots: study_case_model/unit_networks_solves/snapshots/
  unit_networks: study_case_model/unit_networks/
  unit_networks_scenario: study_case_model/unit_networks/scenario_variables/

  unit_gen2_networks: study_case_model/unit_networks_solves/unit_gen2_networks/
  unit_gen2_maps: data/data_analysis_results/unit_gen2_maps/
  unit_networks_folder: data/data_analysis_results/unit_networks
  other_experiment_data: scenario_variables/other_experiment_data/


  # Compare models paths
  compare_models_scenario_bigger: study_case_model/scenario_variables/compare_models/bigger_network/
  compare_models_scenario_smaller: study_case_model/scenario_variables/compare_models/smaller_network/
  compare_models_scenario_study_case: study_case_model/scenario_variables/compare_models/study_case_network/
  compare_models_figures_bigger: study_case_model/figures/compare_models/bigger_network/
  compare_models_figures_smaller: study_case_model/figures/compare_models/smaller_network/
  compare_models_figures_study_case: study_case_model/figures/compare_models/study_case_network/

  # Figure folders
  other_experiments_figures: study_case_model/figures/other_experiments/
  figures_density_impact: study_case_model/figures/density_impact/
  figures_solve_times: study_case_model/figures/solve_times/
  figures_unit_networks: study_case_model/figures/unit_networks/
  figures_unit_pickles: study_case_model/figures/unit_network_pickles/